# Praktikum Pertemuan 1: NumPy dan Pandas

Notebook pendamping Modul Praktikum Penambangan Data. Jalankan sel secara berurutan menggunakan **Shift + Enter**.

**Nama:** Hafidz Rizqullah Prasetya  
**NIM:** 24/535493/SV/24243  
**Kelas:** PL5A1

## Tujuan
1. Memahami array NumPy dan operasi manipulasi array.
2. Membuat serta memanipulasi DataFrame pandas.
3. Menerapkan NumPy dan pandas untuk mengolah data.

> **Catatan:** NumPy dan pandas sudah tersedia di Google Colab. Sel instalasi di bawah hanya dijalankan jika library belum tersedia.

In [4]:
import numpy as np
import pandas as pd

print('NumPy:', np.__version__)
print('pandas:', pd.__version__)

NumPy: 2.4.6
pandas: 3.0.5

# A. NumPy

NumPy menggunakan struktur utama bernama `ndarray`. Indeks array dimulai dari 0.

In [5]:
# Array 1 dimensi
array_1d = np.array([10, 20, 30, 40, 50])
array_1d

array([10, 20, 30, 40, 50])

In [6]:
# Shape menunjukkan banyak elemen pada setiap dimensi
print('shape:', array_1d.shape)
print('ndim:', array_1d.ndim)
print('dtype:', array_1d.dtype)

shape: (5,)
ndim: 1
dtype: int64

In [7]:
# Array 2 dimensi
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
print('shape:', array_2d.shape)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)

In [8]:
# Array 3 dimensi
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(array_3d)
print('shape:', array_3d.shape)

# Array dengan elemen String
array_string = np.array(['Python', 'NumPy', 'Pandas'])
print(array_string)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
['Python' 'NumPy' 'Pandas']

## Indexing dan slicing

Gunakan format `array[indeks]` untuk array 1D, `array[baris, kolom]` untuk array 2D, dan tambahkan indeks sesuai jumlah dimensinya.

In [9]:
print('array 1D indeks 0:', array_1d[0])
print('array 1D indeks terakhir:', array_1d[-1])
print('array 2D baris 1 kolom 2:', array_2d[1, 2])
print('array 3D [sumbu0, sumbu1, sumbu2]:', array_3d[1, 0, 1])
print('slicing array 1D:', array_1d[1:4])
print('slicing array 2D:', array_2d[:, 1:])

array 1D indeks 0: 10
array 1D indeks terakhir: 50
array 2D baris 1 kolom 2: 6
array 3D [sumbu0, sumbu1, sumbu2]: 6
slicing array 1D: [20 30 40]
slicing array 2D: [[2 3]
 [5 6]]

In [10]:
# Contoh array 3D untuk slicing target nilai 3 dan 0
contoh_3d = np.array([
    [[1, 2], [0, 0], [0, 0]],
    [[0, 0], [0, 0], [0, 0]],
    [[8, 9], [3, 4], [0, 5]],
    [[0, 0], [0, 0], [0, 0]]
])
target = contoh_3d[2, 1:, 0]
print('shape:', contoh_3d.shape)
print('hasil slicing [2, 1:, 0]:', target)

shape: (4, 3, 2)
hasil slicing [2, 1:, 0]: [3 0]

## Konversi tipe data dan reshape

Jumlah seluruh elemen harus tetap sama ketika melakukan `reshape`. Nilai `-1` dapat digunakan agar NumPy menghitung ukuran dimensi secara otomatis.

In [11]:
angka = np.array([1, 2, 3, 4])
print('sebelum:', angka.dtype)
print('sesudah:', angka.astype(float).dtype)

array_12 = np.arange(1, 13)
array_3x4 = array_12.reshape(3, 4)
print('reshape 3x4:\n', array_3x4)
print('kembali 1D:', array_3x4.reshape(-1))
print('flatten:', array_3x4.flatten())

sebelum: int64
sesudah: float64
reshape 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
kembali 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]

In [12]:
# Perbedaan len() dan shape
array_4x2x3 = np.zeros((4, 2, 3))
print('len:', len(array_4x2x3))
print('shape:', array_4x2x3.shape)

len: 4
shape: (4, 2, 3)

In [13]:
# Iterasi ndarray
for nilai in array_1d:
    print(nilai)

print('Iterasi dengan indeks:')
for i in range(len(array_1d)):
    print(f'indeks {i}: {array_1d[i]}')

10
20
30
40
50
Iterasi dengan indeks:
indeks 0: 10
indeks 1: 20
indeks 2: 30
indeks 3: 40
indeks 4: 50

## Join, split, search, sorting, dan operasi numerik

In [14]:
kiri_1d = np.array([1, 2, 3])
kanan_1d = np.array([4, 5, 6])
print('join 1D:', np.concatenate((kiri_1d, kanan_1d)))

atas = np.array([[1, 2], [3, 4]])
bawah = np.array([[5, 6], [7, 8]])
print('join axis=0:\n', np.concatenate((atas, bawah), axis=0))
print('join axis=1:\n', np.concatenate((atas, bawah), axis=1))

print('split:', np.array_split(np.arange(1, 10), 3))

join 1D: [1 2 3 4 5 6]
join axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
join axis=1:
 [[1 2 5 6]
 [3 4 7 8]]
split: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [15]:
data = np.array([4, 1, 7, 2, 7, 9])
print('indeks nilai > 5:', np.where(data > 5))
print('indeks nilai 7:', np.where(data == 7))
print('sorting ascending:', np.sort(data))

np.random.seed(42)
random_1d = np.random.rand(2)
random_2d = np.random.rand(2, 3)
print('random 1D:', random_1d)
print('random 2D:\n', random_2d)

indeks nilai > 5: (array([2, 4, 5]),)
indeks nilai 7: (array([2, 4]),)
sorting ascending: [1 2 4 7 7 9]
random 1D: [0.37454012 0.95071431]
random 2D:
 [[0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615]]

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('add:', np.add(a, b))
print('sum seluruh elemen:', np.sum(a))
print('product seluruh elemen:', np.prod(a))

add: [5 7 9]
sum seluruh elemen: 6
product seluruh elemen: 6

# B. DataFrame Pandas

`DataFrame` adalah struktur data tabel dua dimensi pada pandas.

In [16]:
# Membuat DataFrame dari list
df = pd.DataFrame([
    ['Andi', 'Programmer', 8000000],
    ['Budi', 'Analis', 7000000],
    ['Citra', 'Programmer', 9000000]
], columns=['Nama', 'Pekerjaan', 'Gaji'], index=['karyawan-1', 'karyawan-2', 'karyawan-3'])
df

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-2   Budi      Analis  7000000
karyawan-3  Citra  Programmer  9000000

In [17]:
# Menambah kolom dengan assignment, insert, assign, dan dictionary
df_tambah = df.copy()
df_tambah['Status'] = ['Tetap', 'Kontrak', 'Tetap']
df_tambah.insert(1, 'Kota', ['Sleman', 'Bantul', 'Kota Yogyakarta'])
df_tambah = df_tambah.assign(
    Pengalaman=[2, 1, 3], Aktif=[True, True, True]
)
df_tambah

,Nama,Kota,Pekerjaan,Gaji,Status,Pengalaman,Aktif
karyawan-1,Andi,Sleman,Programmer,8000000,Tetap,2,True
karyawan-2,Budi,Bantul,Analis,7000000,Kontrak,1,True
karyawan-3,Citra,Kota Yogyakarta,Programmer,9000000,Tetap,3,True

In [18]:
# Menambah beberapa kolom sekaligus dengan dictionary
df_multi = df.copy()
kolom_baru = pd.DataFrame({
    'Status': ['Tetap', 'Kontrak', 'Tetap'],
    'Bonus': [1000000, 500000, 1200000]
}, index=df_multi.index)
df_multi = pd.concat([df_multi, kolom_baru], axis=1)
df_multi

             Nama   Pekerjaan     Gaji   Status    Bonus
karyawan-1   Andi  Programmer  8000000    Tetap  1000000
karyawan-2   Budi      Analis  7000000  Kontrak   500000
karyawan-3  Citra  Programmer  9000000    Tetap  1200000

In [19]:
# Menghapus kolom dengan drop, pop, dan del
df_hapus = df_multi.copy()
df_hapus.drop(columns='Bonus', inplace=True)
status_dihapus = df_hapus.pop('Status')
df_hapus['KolomSementara'] = 1
del df_hapus['KolomSementara']
print(df_hapus)
print('Kolom hasil pop:', status_dihapus.tolist())

df_multi_kolom = df_multi.drop(columns=['Status', 'Bonus'])
df_multi_kolom

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-2   Budi      Analis  7000000
karyawan-3  Citra  Programmer  9000000
Kolom hasil pop: ['Tetap', 'Kontrak', 'Tetap']

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-2   Budi      Analis  7000000
karyawan-3  Citra  Programmer  9000000

In [20]:
# Sorting berdasarkan indeks dan nilai
df_sort = df_multi.copy()
df_sort.index = [3, 1, 2]
print('sort index baris:')
display(df_sort.sort_index())
print('sort index kolom:')
display(df_sort.sort_index(axis=1))
print('sort berdasarkan Gaji descending:')
display(df_sort.sort_values(by='Gaji', ascending=False))

sort index baris:

    Nama   Pekerjaan     Gaji   Status    Bonus
1   Budi      Analis  7000000  Kontrak   500000
2  Citra  Programmer  9000000    Tetap  1200000
3   Andi  Programmer  8000000    Tetap  1000000

sort index kolom:

     Bonus     Gaji   Nama   Pekerjaan   Status
3  1000000  8000000   Andi  Programmer    Tetap
1   500000  7000000   Budi      Analis  Kontrak
2  1200000  9000000  Citra  Programmer    Tetap

sort berdasarkan Gaji descending:

    Nama   Pekerjaan     Gaji   Status    Bonus
2  Citra  Programmer  9000000    Tetap  1200000
3   Andi  Programmer  8000000    Tetap  1000000
1   Budi      Analis  7000000  Kontrak   500000

In [21]:
# Filtering: kondisi tunggal, multiple conditions, isin, query, dan str.contains
print('Gaji >= 8 juta:')
display(df[df['Gaji'] >= 8000000])
print('Programmer dan gaji >= 8 juta:')
display(df[(df['Pekerjaan'] == 'Programmer') & (df['Gaji'] >= 8000000)])
print('Pekerjaan tertentu dengan isin:')
display(df[df['Pekerjaan'].isin(['Programmer', 'Analis'])])
print('Query:')
display(df.query("Gaji > 7500000"))
print('Nama mengandung huruf i:')
display(df[df['Nama'].str.contains('i', case=False, na=False)])

Gaji >= 8 juta:

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-3  Citra  Programmer  9000000

Programmer dan gaji >= 8 juta:

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-3  Citra  Programmer  9000000

Pekerjaan tertentu dengan isin:

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-2   Budi      Analis  7000000
karyawan-3  Citra  Programmer  9000000

Query:

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-3  Citra  Programmer  9000000

Nama mengandung huruf i:

             Nama   Pekerjaan     Gaji
karyawan-1   Andi  Programmer  8000000
karyawan-2   Budi      Analis  7000000
karyawan-3  Citra  Programmer  9000000

## Grouping dan aggregation

In [22]:
data_karyawan = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Citra', 'Deni', 'Eka', 'Fajar'],
    'Pekerjaan': ['Programmer', 'Analis', 'Programmer', 'Analis', 'Desainer', 'Programmer'],
    'Umur': [23, 28, 25, 31, 24, 27],
    'Gaji': [8000000, 7000000, 9000000, 7500000, 6500000, 8500000]
})
kelompok = data_karyawan.groupby('Pekerjaan')
print('groups:', kelompok.groups)

for pekerjaan, group in kelompok:
    print(f'\n{pekerjaan}:')
    display(group)

print('Satu kelompok:')
display(kelompok.get_group('Programmer'))

groups: {'Analis': [1, 3], 'Desainer': [4], 'Programmer': [0, 2, 5]}

Analis:

   Nama Pekerjaan  Umur     Gaji
1  Budi    Analis    28  7000000
3  Deni    Analis    31  7500000

Desainer:

  Nama Pekerjaan  Umur     Gaji
4  Eka  Desainer    24  6500000

Programmer:

    Nama   Pekerjaan  Umur     Gaji
0   Andi  Programmer    23  8000000
2  Citra  Programmer    25  9000000
5  Fajar  Programmer    27  8500000

Satu kelompok:

    Nama   Pekerjaan  Umur     Gaji
0   Andi  Programmer    23  8000000
2  Citra  Programmer    25  9000000
5  Fajar  Programmer    27  8500000

In [23]:
print('Mean umur dan gaji per pekerjaan:')
display(kelompok[['Umur', 'Gaji']].mean())

print('Aggregation beberapa fungsi:')
display(kelompok.agg({
    'Umur': ['mean', 'min', 'max'],
    'Gaji': ['mean', 'sum', 'std']
}))

Mean umur dan gaji per pekerjaan:

            Umur       Gaji
Pekerjaan
Analis      29.5  7250000.0
Desainer    24.0  6500000.0
Programmer  25.0  8500000.0

Aggregation beberapa fungsi:

            Umur               Gaji
            mean min max       mean       sum            std
Pekerjaan
Analis      29.5  28  31  7250000.0  14500000  353553.390593
Desainer    24.0  24  24  6500000.0   6500000            NaN
Programmer  25.0  23  27  8500000.0  25500000  500000.000000

## Merge, join, concatenate, dan indeks

In [24]:
karyawan = pd.DataFrame({
    'Emp_id': ['E01', 'E02', 'E03'],
    'Nama': ['Andi', 'Budi', 'Citra'],
    'Divisi': ['Data', 'IT', 'Data']
})
gaji = pd.DataFrame({
    'ID': ['E01', 'E02', 'E04'],
    'Gaji': [8000000, 7000000, 6000000],
    'Status': ['Tetap', 'Kontrak', 'Tetap']
})

hasil_merge = pd.merge(
    karyawan, gaji, left_on='Emp_id', right_on='ID',
    how='left', sort=True, suffixes=('_karyawan', '_gaji')
)
hasil_merge

  Emp_id   Nama Divisi   ID       Gaji   Status
0    E01   Andi   Data  E01  8000000.0    Tetap
1    E02   Budi     IT  E02  7000000.0  Kontrak
2    E03  Citra   Data  NaN        NaN      NaN

In [25]:
# Join berbasis indeks
karyawan_index = karyawan.set_index('Emp_id')
gaji_index = gaji.set_index('ID')
hasil_join = karyawan_index.join(gaji_index, how='left', rsuffix='_gaji')
hasil_join

         Nama Divisi       Gaji   Status
Emp_id
E01      Andi   Data  8000000.0    Tetap
E02      Budi     IT  7000000.0  Kontrak
E03     Citra   Data        NaN      NaN

In [26]:
data_tambahan = pd.DataFrame({
    'Nama': ['Deni'], 'Pekerjaan': ['Tester'], 'Gaji': [6500000]
})
print('Concatenate vertikal:')
display(pd.concat([df, data_tambahan], axis=0, ignore_index=True))

kiri = pd.DataFrame({'Nama': ['Andi', 'Budi'], 'Kota': ['Sleman', 'Bantul']})
kanan = pd.DataFrame({'Gaji': [8000000, 7000000], 'Status': ['Tetap', 'Kontrak']})
print('Concatenate horizontal:')
display(pd.concat([kiri, kanan], axis=1))

berbeda_kolom = pd.DataFrame({'Nama': ['Eka'], 'Bonus': [500000]})
print('Concatenate outer menghasilkan NaN pada kolom yang tidak tersedia:')
display(pd.concat([kiri, berbeda_kolom], join='outer', ignore_index=True))

Concatenate vertikal:

    Nama   Pekerjaan     Gaji
0   Andi  Programmer  8000000
1   Budi      Analis  7000000
2  Citra  Programmer  9000000
3   Deni      Tester  6500000

Concatenate horizontal:

   Nama    Kota     Gaji   Status
0  Andi  Sleman  8000000    Tetap
1  Budi  Bantul  7000000  Kontrak

Concatenate outer menghasilkan NaN pada kolom yang tidak tersedia:

   Nama    Kota     Bonus
0  Andi  Sleman       NaN
1  Budi  Bantul       NaN
2   Eka     NaN  500000.0

In [27]:
# Reset index dan set index
gabungan = pd.concat([karyawan, karyawan], ignore_index=True)
print('reset saat concat:')
display(gabungan)

reset = hasil_merge.reset_index(drop=True)
print('reset_index(drop=True):')
display(reset)

dengan_index = hasil_merge.set_index('Emp_id')
print('set_index dan akses loc:')
display(dengan_index.loc['E02'])

reset saat concat:

  Emp_id   Nama Divisi
0    E01   Andi   Data
1    E02   Budi     IT
2    E03  Citra   Data
3    E01   Andi   Data
4    E02   Budi     IT
5    E03  Citra   Data

reset_index(drop=True):

  Emp_id   Nama Divisi   ID       Gaji   Status
0    E01   Andi   Data  E01  8000000.0    Tetap
1    E02   Budi     IT  E02  7000000.0  Kontrak
2    E03  Citra   Data  NaN        NaN      NaN

set_index dan akses loc:

Nama           Budi
Divisi           IT
ID              E02
Gaji      7000000.0
Status      Kontrak
Name: E02, dtype: object

## Pivot table, melt, dan lambda

In [28]:
data_pivot = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Citra', 'Deni', 'Eka', 'Fajar'],
    'Gender': ['L', 'L', 'P', 'L', 'P', 'L'],
    'Pekerjaan': ['Programmer', 'Analis', 'Programmer', 'Analis', 'Desainer', 'Programmer'],
    'Gaji': [8, 7, 9, 7.5, 6.5, 8.5]
})
pivot = pd.pivot_table(
    data_pivot, values='Gaji', index='Pekerjaan',
    columns='Gender', aggfunc=[np.sum, np.mean]
)
pivot

             sum       mean
Gender         L    P     L    P
Pekerjaan
Analis      14.5  NaN  7.25  NaN
Desainer     NaN  6.5   NaN  6.5
Programmer  16.5  9.0  8.25  9.0

In [29]:
nilai = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Citra'],
    'Matematika': [80, 75, 90],
    'Bahasa': [85, 80, 88]
})
nilai_long = pd.melt(
    nilai, id_vars=['Nama'],
    value_vars=['Matematika', 'Bahasa'],
    var_name='Mata Pelajaran', value_name='Nilai'
)
nilai_long

    Nama Mata Pelajaran  Nilai
0   Andi     Matematika     80
1   Budi     Matematika     75
2  Citra     Matematika     90
3   Andi         Bahasa     85
4   Budi         Bahasa     80
5  Citra         Bahasa     88

In [28]:
jumlah = lambda x, y: x + y
kali = lambda x: x * 2
print('lambda jumlah:', jumlah(4, 6))
print('lambda kali:', kali(5))

nilai['Kategori'] = nilai['Matematika'].apply(
    lambda skor: 'A' if skor >= 85 else ('B' if skor >= 75 else 'C')
)
nilai

lambda jumlah: 10
lambda kali: 10

    Nama  Matematika  Bahasa Kategori
0   Andi          80      85        B
1   Budi          75      80        B
2  Citra          90      88        A

## Membaca file CSV dari Google Drive

Jika dataset ada di Google Drive, jalankan sel berikut lalu sesuaikan lokasi file.

In [30]:
# Hubungkan Google Drive jika notebook dijalankan di Google Colab
try:
    from google.colab import drive
    drive.mount('/content/drive')
    folder_data = '/content/drive/MyDrive'
    print('Mode Google Colab aktif')
except ModuleNotFoundError:
    from pathlib import Path
    folder_data = str(Path.cwd())
    print('Mode lokal VS Code aktif; gunakan file di folder notebook')

Mode lokal VS Code aktif; gunakan file di folder notebook

In [31]:
# Ganti nama/path dataset sesuai lokasi file
from pathlib import Path
path_dataset = Path(folder_data) / 'dataset.csv'
if path_dataset.exists():
    dataset = pd.read_csv(path_dataset)
    display(dataset.head())
else:
    print(f'Dataset belum ditemukan: {path_dataset}')

# Contoh membaca CSV lokal yang dibuat dari DataFrame
contoh_path = Path(folder_data) / 'contoh_karyawan.csv'
data_karyawan.to_csv(contoh_path, index=False)
dataset_contoh = pd.read_csv(contoh_path)
dataset_contoh.head()

Dataset belum ditemukan: /home/hafidzprasetya/Kuliah/PPD/pertemuan-1/dataset.csv

    Nama   Pekerjaan  Umur     Gaji
0   Andi  Programmer    23  8000000
1   Budi      Analis    28  7000000
2  Citra  Programmer    25  9000000
3   Deni      Analis    31  7500000
4    Eka    Desainer    24  6500000

# C. Tugas dan Analisis

Kerjakan setiap tugas di sel kosong berikut. Sel solusi dapat digunakan untuk mengecek jawaban setelah mencoba sendiri.

## Tugas 1
Buat array NumPy 2D berukuran 4x4 berisi angka acak 0-50, ubah menjadi array 2x8, lalu tampilkan elemen yang bernilai lebih dari 25.

In [31]:
# Tulis jawabanmu di sini
# np.random.seed(1)
# tugas_1 = ...

In [32]:
# Solusi referensi Tugas 1
np.random.seed(1)
tugas_1 = np.random.randint(0, 51, size=(4, 4))
tugas_1_2x8 = tugas_1.reshape(2, 8)
print('Array 4x4:\n', tugas_1)
print('Array 2x8:\n', tugas_1_2x8)
print('Elemen > 25:', tugas_1_2x8[tugas_1_2x8 > 25])

Array 4x4:
 [[37 43 12  8]
 [ 9 11  5 15]
 [ 0 16  1 12]
 [ 7 45  6 25]]
Array 2x8:
 [[37 43 12  8  9 11  5 15]
 [ 0 16  1 12  7 45  6 25]]
Elemen > 25: [37 43 45]

## Tugas 2
Buat DataFrame karyawan dengan kolom `Nama`, `Pekerjaan`, dan `Gaji`. Kelompokkan berdasarkan `Pekerjaan`, lalu hitung maksimum, minimum, dan standar deviasi `Gaji` menggunakan `agg()`.

In [33]:
# Tulis jawabanmu di sini
# tugas_2 = pd.DataFrame(...)
# hasil_tugas_2 = tugas_2.groupby('Pekerjaan').agg(...)

In [33]:
# Solusi referensi Tugas 2
tugas_2 = pd.DataFrame({
    'Nama': ['Ana', 'Bima', 'Caca', 'Dodi', 'Evi'],
    'Pekerjaan': ['Programmer', 'Analis', 'Programmer', 'Analis', 'Desainer'],
    'Gaji': [8000000, 7000000, 9000000, 7500000, 6500000]
})
hasil_tugas_2 = tugas_2.groupby('Pekerjaan').agg(
    Gaji_maksimum=('Gaji', 'max'),
    Gaji_minimum=('Gaji', 'min'),
    Gaji_std=('Gaji', 'std')
)
display(tugas_2)
display(hasil_tugas_2)

   Nama   Pekerjaan     Gaji
0   Ana  Programmer  8000000
1  Bima      Analis  7000000
2  Caca  Programmer  9000000
3  Dodi      Analis  7500000
4   Evi    Desainer  6500000

            Gaji_maksimum  Gaji_minimum       Gaji_std
Pekerjaan
Analis            7500000       7000000  353553.390593
Desainer          6500000       6500000            NaN
Programmer        9000000       8000000  707106.781187

## Tugas 3
Buat DataFrame karyawan dengan kolom `Emp_id`, `Nama`, dan `Divisi`, serta DataFrame gaji dengan kolom `ID`, `Gaji`, dan `Status`. Masing-masing minimal tiga baris. Gabungkan dengan `merge()` menggunakan `left_on='Emp_id'`, `right_on='ID'`, `how='left'`, dan `suffixes`.

In [35]:
# Tulis jawabanmu di sini
# karyawan_tugas = pd.DataFrame(...)
# gaji_tugas = pd.DataFrame(...)
# hasil_tugas_3 = pd.merge(...)

In [34]:
# Solusi referensi Tugas 3
karyawan_tugas = pd.DataFrame({
    'Emp_id': ['E01', 'E02', 'E03'],
    'Nama': ['Ana', 'Bima', 'Caca'],
    'Divisi': ['Data', 'IT', 'Data']
})
gaji_tugas = pd.DataFrame({
    'ID': ['E01', 'E02', 'E04'],
    'Gaji': [8000000, 7000000, 6000000],
    'Status': ['Tetap', 'Kontrak', 'Tetap']
})
hasil_tugas_3 = pd.merge(
    karyawan_tugas, gaji_tugas,
    left_on='Emp_id', right_on='ID', how='left',
    suffixes=('_karyawan', '_gaji')
)
display(hasil_tugas_3)

  Emp_id  Nama Divisi   ID       Gaji   Status
0    E01   Ana   Data  E01  8000000.0    Tetap
1    E02  Bima     IT  E02  7000000.0  Kontrak
2    E03  Caca   Data  NaN        NaN      NaN

## Kesimpulan

Berdasarkan praktikum yang telah saya lakukan, saya memahami beberapa hal berikut:

1. `len()` pada NumPy hanya menunjukkan jumlah elemen pada sumbu pertama, sedangkan `shape` menunjukkan ukuran array pada seluruh dimensinya. Sebagai contoh, array dengan bentuk `(4, 2, 3)` memiliki `len()` sebesar 4 dan `shape` `(4, 2, 3)`.
2. Fungsi `groupby()` pada pandas digunakan untuk mengelompokkan data berdasarkan kategori tertentu. Setelah dikelompokkan, data dapat diringkas menggunakan fungsi aggregation seperti `mean()`, `sum()`, `min()`, `max()`, dan `std()`.
3. Fungsi `merge()` menggabungkan DataFrame berdasarkan kolom kunci, sedangkan `join()` umumnya menggabungkan DataFrame berdasarkan indeks. Pada `left join`, seluruh baris dari DataFrame sebelah kiri tetap dipertahankan.
4. Saya juga memahami bahwa NumPy cocok untuk operasi numerik pada array, sedangkan pandas memudahkan pengolahan data tabular menggunakan Series dan DataFrame.